# https://github.com/mochajs/mocha/blob/master/example/config/.mocharc.yml
extension:
  - 'js'
ignore:
  - node_modules
  - src
reporter: spec
require: '@babel/register'
spec: spec/**/*.spec.js
watch-files:
  - lib/**/*.js
  - spec/**/*.js
watch-ignore:
  - node_modules
  - src
