# https://github.com/mochajs/mocha/blob/master/example/config/.mocharc.yml
extension:
  - ts
ignore: &ignore
  - coverage
  - dist
  - node_modules
  - .nyc_output
  - src
  - types
reporter: spec
require: ts-node/register
spec: spec/**/*.spec.ts
watch-files:
  - spec/**/*.ts
  - src/**/*.ts
watch-ignore: *ignore
